"""Initial migration

Revision ID: a2311e3b2d49
Revises: 4d034baec530
Create Date: 2026-03-02 09:37:46.201666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2311e3b2d49'
down_revision: Union[str, Sequence[str], None] = '4d034baec530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_id'), 'hospitals', ['id'], unique=False)
    op.create_table('ngos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ngos_id'), 'ngos', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('patient', 'admin', name='user_roles'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('ambulances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('ngo_id', sa.Integer(), nullable=True),
    sa.Column('driver_name', sa.String(length=255), nullable=True),
    sa.Column('driver_phone', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('available', 'assigned', 'en_route', 'at_scene', 'transporting', 'maintenance', name='ambulance_status'), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ambulance_status_location', 'ambulances', ['status', 'latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_ambulances_hospital_id'), 'ambulances', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_ambulances_id'), 'ambulances', ['id'], unique=False)
    op.create_index(op.f('ix_ambulances_latitude'), 'ambulances', ['latitude'], unique=False)
    op.create_index(op.f('ix_ambulances_longitude'), 'ambulances', ['longitude'], unique=False)
    op.create_index(op.f('ix_ambulances_ngo_id'), 'ambulances', ['ngo_id'], unique=False)
    op.create_index(op.f('ix_ambulances_status'), 'ambulances', ['status'], unique=False)
    op.create_table('bed_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('bed_type', sa.String(length=50), nullable=False),
    sa.Column('total_beds', sa.Integer(), nullable=False),
    sa.Column('available_beds', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('available_beds <= total_beds', name='check_available_le_total'),
    sa.CheckConstraint('available_beds >= 0', name='check_available_beds_positive'),
    sa.CheckConstraint('total_beds >= 0', name='check_total_beds_positive'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'bed_type', name='uq_hospital_bedtype')
    )
    op.create_index(op.f('ix_bed_inventory_bed_type'), 'bed_inventory', ['bed_type'], unique=False)
    op.create_index(op.f('ix_bed_inventory_hospital_id'), 'bed_inventory', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_bed_inventory_id'), 'bed_inventory', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('emergency_contact_number', sa.String(length=20), nullable=True),
    sa.Column('is_self', sa.Boolean(), nullable=False),
    sa.Column('relation', sa.String(length=50), nullable=True),
    sa.Column('critical_information', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('age >= 0', name='check_patient_age_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_user_id'), 'patients', ['user_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('ambulance_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('ambulance_requested', sa.Boolean(), nullable=True),
    sa.Column('user_latitude', sa.String(length=50), nullable=True),
    sa.Column('user_longitude', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', 'completed', name='booking_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_reasoning', sa.JSON(), nullable=True),
    sa.Column('triage_level', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('orchestration_notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['ambulance_id'], ['ambulances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_ambulance_id'), 'bookings', ['ambulance_id'], unique=False)
    op.create_index(op.f('ix_bookings_hospital_id'), 'bookings', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_patient_id'), 'bookings', ['patient_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_patient_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_hospital_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_ambulance_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_patients_user_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_bed_inventory_id'), table_name='bed_inventory')
    op.drop_index(op.f('ix_bed_inventory_hospital_id'), table_name='bed_inventory')
    op.drop_index(op.f('ix_bed_inventory_bed_type'), table_name='bed_inventory')
    op.drop_table('bed_inventory')
    op.drop_index(op.f('ix_ambulances_status'), table_name='ambulances')
    op.drop_index(op.f('ix_ambulances_ngo_id'), table_name='ambulances')
    op.drop_index(op.f('ix_ambulances_longitude'), table_name='ambulances')
    op.drop_index(op.f('ix_ambulances_latitude'), table_name='ambulances')
    op.drop_index(op.f('ix_ambulances_id'), table_name='ambulances')
    op.drop_index(op.f('ix_ambulances_hospital_id'), table_name='ambulances')
    op.drop_index('idx_ambulance_status_location', table_name='ambulances')
    op.drop_table('ambulances')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ngos_id'), table_name='ngos')
    op.drop_table('ngos')
    op.drop_index(op.f('ix_hospitals_id'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
